# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: a80fdf3b893def0c8b9a81597ba45d78c7a8bf9f $
Configuration parameters:
  url = http://es.steven-universe-fanon.wikia.com/wiki/Wikia_Steven_Universe_Fanon
  name = stevenfanon

Please do not commit this to the Git repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'stevenfanon'
        self.langs = {
            'es': 'es.steven-universe-fanon.wikia.com',
        }

        self.namespaces[2] = self.namespaces.get(2, {})
        self.namespaces[2][u'es'] = [u'Usuaria']
        self.namespaces[3] = self.namespaces.get(3, {})
        self.namespaces[3][u'es'] = [u'Usuario Discusi\xf3n', u'Usuaria Discusi\xf3n']
        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'es'] = [u'Steven Universe Fanon Wikia']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'es'] = [u'Steven Universe Fanon Wikia discusi\xf3n']
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'es'] = [u'Image', u'Imagen']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'es'] = [u'Image talk', u'Imagen Discusi\xf3n']
        self.namespaces[1200] = self.namespaces.get(1200, {})
        self.namespaces[1200][u'es'] = [u'Muro', u'Message Wall']
        self.namespaces[1201] = self.namespaces.get(1201, {})
        self.namespaces[1201][u'es'] = [u'Hilo', u'Thread']
        self.namespaces[1202] = self.namespaces.get(1202, {})
        self.namespaces[1202][u'es'] = [u'Bienvenida del Muro', u'Message Wall Greeting']
        self.namespaces[828] = self.namespaces.get(828, {})
        self.namespaces[828][u'es'] = [u'M\xf3dulo']
        self.namespaces[829] = self.namespaces.get(829, {})
        self.namespaces[829][u'es'] = [u'M\xf3dulo discusi\xf3n']
        self.namespaces[701] = self.namespaces.get(701, {})
        self.namespaces[701][u'es'] = [u'10 Mejores Discusi\xf3n', u'Top 10 list talk']
        self.namespaces[2000] = self.namespaces.get(2000, {})
        self.namespaces[2000][u'es'] = [u'Subforo', u'Board']
        self.namespaces[2001] = self.namespaces.get(2001, {})
        self.namespaces[2001][u'es'] = [u'Tema del foro', u'Board Thread']
        self.namespaces[2002] = self.namespaces.get(2002, {})
        self.namespaces[2002][u'es'] = [u'Tema', u'Topic']
        self.namespaces[700] = self.namespaces.get(700, {})
        self.namespaces[700][u'es'] = [u'10 Mejores', u'Top 10 list']
        self.namespaces[110] = self.namespaces.get(110, {})
        self.namespaces[110][u'es'] = [u'Foro', u'Forum']
        self.namespaces[111] = self.namespaces.get(111, {})
        self.namespaces[111][u'es'] = [u'Foro Discusi\xf3n', u'Forum talk']
        self.namespaces[500] = self.namespaces.get(500, {})
        self.namespaces[500][u'es'] = [u'Usuario Blog', u'User blog']
        self.namespaces[501] = self.namespaces.get(501, {})
        self.namespaces[501][u'es'] = [u'Usuario Blog Comentario', u'User blog comment']
        self.namespaces[502] = self.namespaces.get(502, {})
        self.namespaces[502][u'es'] = [u'Blog']
        self.namespaces[503] = self.namespaces.get(503, {})
        self.namespaces[503][u'es'] = [u'Blog Discusi\xf3n', u'Blog talk']


    def scriptpath(self, code):
        return {
            'es': '',
        }[code]

    def version(self, code):
        return {
            'es': u'1.19.24',
        }[code]
